spring:
  data:
    mongodb:
      username: harianbu
      password: harianbu@3
      host: localhost
      port: 27017
      database: HariMart-ms-notification
      authentication-database: admin

security:
  authorization: enabled

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      notification-service:
        base-config: default
        sliding-window-size: 20
        failure-rate-threshold: 40
        wait-duration-in-open-state: 15s

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

---
spring:
  profiles: order-consumer

kafka:
  consumer:
    group-id: orderGroup
    properties:
      spring.json.type.mapping: "orderConfirmation:com.hariSolution.kafkaOrder.order.OrderConfirmation"

---
spring:
  profiles: payment-consumer

kafka:
  consumer:
    group-id: paymentGroup
    properties:
      spring.json.type.mapping: "paymentConfirmation:com.hariSolution.payment.PaymentConfirmation"
