server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/hariMart_ms_payment  # Use updated port 5434
    username: postgres
    password: harianbu@3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  application:
    name: payment-service

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
