version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-HariMart-ms
    environment:
      - POSTGRES_DB=hariMart_ms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=harianbu@3
    ports:
      - "5434:5432"
    networks:
      - spring-HariMart-ms-net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-HariMart-ms
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - spring-HariMart-ms-net
    restart: unless-stopped


  mongodb:
    image: mongo
    container_name: mongo-HariMart-ms
    ports:
      - "27017:27017"  # Exposing MongoDB on the default port
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hariharan
      - MONGO_INITDB_ROOT_PASSWORD=harianbu
    networks:
      - spring-HariMart-ms-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-HariMart-ms
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hariharan  # Same as MongoDB root username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=harianbu  # Same as MongoDB root password
      - ME_CONFIG_MONGODB_SERVER=mongo-HariMart-ms  # Use service name for container resolution
    networks:
      - spring-HariMart-ms-net
    restart: unless-stopped
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - spring-HariMart-ms-net

networks:
  spring-HariMart-ms-net:
    driver: bridge

volumes:
  postgres-data: {}  # Named volume for PostgreSQL data persistence
  pgadmin-data: {}   # Named volume for PGAdmin data persistence
  mongo-data: {}     # Volume to persist MongoDB data across container restarts
